DROP TABLE IF EXISTS file_entradas CASCADE;
DROP TABLE IF EXISTS file_restaurantes CASCADE;
DROP TABLE IF EXISTS file_vehiculos CASCADE;
DROP TABLE IF EXISTS file_pasajeros CASCADE;
DROP TABLE IF EXISTS file_guias CASCADE;
